### ISSUE TITLE
gateone-1.1.1.noarch.rpm requires Python 2.6

### ISSUE THREAD

**Issue by cnelissen** [liftoff/GateOne#163]
It seems the RPM you have for download requires Python 2.6 instead of Python 2.6+... I am currently running Python 2.7 and getting an error.

[root@Server ~]# more /etc/redhat-release
     Fedora release 14 (Laughlin)
[root@Server ~]# python -V
     Python 2.7
[root@Server ~]# rpm -hUv https://github.com/downloads/liftoff/GateOne/gateone-1.1-1.noarch.rpm
     Retrieving https://github.com/downloads/liftoff/GateOne/gateone-1.1-1.noarch.rpm
     error: Failed dependencies:
             python(abi) = 2.6 is needed by gateone-1.1-1.noarch

**Comment by ferricoxide** [comment]
I know this is a stupidly-old bug, but didn't want to open a redundant issue.

At any rate, this issue still exists. I'm attempting to deploy GateOne into a CentOS 7 - it's a lot lighter that Guacamole. EL7 derivatives ship with Python 2.7.

I tried grabbing the pre-made RPM to install.

~~~
 curl -o gateone-1.1-1.noarch.rpm -L https://github.com/downloads/liftoff/GateOne/gateone-1.1-1.noarch.rpm
~~~

Since I didn't want to have to install the entire `@Development Tools` RPM-group. Especially wanted to avoid this since this was a production system. Tried to let `yum` install it, in case there were any dependencies to resolve, and got:

~~~
# yum install /tmp/gateone-1.1-1.noarch.rpm
Loaded plugins: fastestmirror
Examining /tmp/gateone-1.1-1.noarch.rpm: gateone-1.1-1.noarch
Marking /tmp/gateone-1.1-1.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package gateone.noarch 0:1.1-1 will be installed
--> Processing Dependency: python(abi) = 2.6 for package: gateone-1.1-1.noarch
Loading mirror speeds from cached hostfile
 * base: mirrors.kernel.org
 * epel: s3-mirror-us-west-2.fedoraproject.org
 * extras: mirror.chpc.utah.edu
 * updates: repos.lax.quadranet.com
--> Finished Dependency Resolution
Error: Package: gateone-1.1-1.noarch (/gateone-1.1-1.noarch)
           Requires: python(abi) = 2.6
           Installed: python-2.7.5-18.el7_1.1.x86_64 (installed)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.5-16.el7.x86_64 (base)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python34-3.4.3-2.el7.x86_64 (epel)
               python(abi) = 3.4
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

~~~
I need to re-deploy my service to a network whose ACLs won't allow port 22. So, I'll probably end up having to spin an instance to run an `rpmbuild` from and transfer it to the production system.

**Comment by ferricoxide** [comment]
Just tried running the `install-rpm.sh` to generate an updated RPM. Looks like the issue is less a problem with how the Python dependency is defined within the downloadable RPM than that Python 2.7 deprecates GateOne's reliance on a Python installation that supports `.pth` files.

**Comment by liftoff** [comment]
Solution:  Don't use the gateone-1.1 RPM.  It's ancient.  Grab the latest Github code and use that.  If want an RPM just make one like so:

    python setup.py bdist_rpm

That will generate an rpm which *should* work fine on CentOS 7.  If not please report back any errors or details about what went wrong and I'll fix it.

**Comment by ferricoxide** [comment]
Yeah. I'd seen the date on it. Was going to try building a new RPM and offer it back via PR, but encountered errors with both the python-bdist and the RPM shell-script. Thus, I opened #560.

Haven't had time to get much further into the problem in #560.

**Comment by 1108080** [comment]
I executed python setup.py bdist_rpm but I didn't find the rpm file under ./dist.  How to deal with?

**Comment by heyxin0** [comment]
@liftoff I executed python setup.py bdist_rpm but I didn't find the rpm file under ./dist.  How to deal with?

**Comment by heyxin0** [comment]
@liftoff 
rpm: /usr/bin/rpmspec: Permission denied
error: Failed to execute: "rpm -q --qf '%{name}-%{version}-%{release}.src.rpm %{arch}/%{name}-%{version}-%{release}.%{arch}.rpm\\n' --specfile 'build/bdist.linux-x86_64/rpm/SPECS/gateone.spec'"
