### ISSUE TITLE
Serious security issue with GateOne

### ISSUE THREAD

**Issue by hetzbh** [liftoff/GateOne#482]
After playing and using GateOne for few days, it seems there is a serious security issue (using pam to authenticate access to GateOne, but it could also be OAuth2 ..)

After closing the browser and opening it, it's just lets the user access GateOne *without* asking for password, so if a user forgets to log out, anyone else who will use the machine, will have full access to the SSH session that are running inside GateOne.

There is the option of expiry time of SSH sessions inside GateOne, but that's not the issue, the issue is the access to the GateOne.

Please add GateOne session timeout, and if I can suggest - make it a default of 1 minute after the user closed the browser/tab. That way, if someone else uses the machine with the same browse and user/pass (which happens on Internet Cafe's etc..), he will need to re-enter user/pass to access GateOne.

**Comment by 123troy** [comment]
My team and I were facing the same issues and we are in a high security environment.  We found that a cookie is being placed on the users server that is being used as a form of trusted authentication.

We made changes to two files and were able to resolve this issue in our environment.  Before I list what we did I would like to note that in Chrome it does not work unless the user and the two following settings are  unchecked.
 1) Settings->On Startup is set to 'Continue where you left off'
 2) Settings->Advanced Settings->System->Continue Running background apps... is 'checked'

The first item that we did was going into /usr/lib/python2.6/site-packages/gateone-1.2.0-py2.6.egg/gateone/core/server.py  and replacing all values of 14d with 1d.  This is so that if the second item fails, the cert will expire after a day.

The second item was we modified the /usr/lib/python2.6/site-packages/gateone-1.2.0-py2.6.egg/gateone/templates/index.html to the following below so that the cookie expires at the end of the session even if the user just closes the browser.

Index.html
```
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="target-densitydpi=device-dpi, width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=0" />
{% if location == 'default' %}
    <title>Gate One - {{hostname}}</title>
{% else %}
    <title>Gate One - {{location}}</title>
{% end %}
    <link rel="stylesheet" href="{{url_prefix}}static/gateone.css" type="text/css" media="screen" />
    <link rel="shortcut icon" href="{{url_prefix}}static/favicon.ico" />
    {% raw head %}
</head>
<body>
{% raw body %}
<script type="text/javascript" src="{{gateone_js}}"></script>
<div id="gateone"></div>
<script>
window.onload = function() {
    // Initialize Gate One using defaults:
    GateOne.location = '{{location}}';
{% if prefs %}
    var urlPrefs = {% raw prefs %};
    for (var pref in urlPrefs) {
        GateOne.prefs[pref] = urlPrefs[pref];
    }
    // Also remove the long obtrusive query string from the URL
    GateOne.Utils.removeQueryVariable('prefs');
{% end %}
    GateOne.init({% raw js_init %}); // NOTE: Many defaults (e.g. CSS themes/colors, font size, etc) can be overridden by the user.

    // ################### BEGIN - ADD #####################
    //
    // Delete the expiration date of the gateone_user cookie. If a cookie does not have
    // an expiration date, the browser will delete the cookie when the browser is closed.
    // Deleting the cookie means that the user will be promped again for user id and password when
    // they login again after closing their browser. This was added so that the user is effectively logged
    // out when they close the browser. Note that on Chrome, closing the browser will not delete the cookie
    // if one of the 2 following settings is set:
    //   1) Settings->On Startup is set to 'Continue where you left off'
    //   2) Settings->Advanced Settings->System->Continue Running background apps... is 'checked'
    //
    // In addition to the change in this file, /usr/lib/python2.6/site-packages/gateone-1.2.0-py2.6.egg/gateone/core/server.py
    // to change the cookie expiration date from a default of 14d to 1d. This way if the browser does not
    // delete the cookies on close (Chrome) they will still be logged out after 1 day.
    //
    deleteCookieExpiration('gateone_user');
    //
    // ################### END - ADD #####################

    // Commented out below are a few examples of the various ways you can initialize Gate One...
    // Init Gate One (client) using the built-in white CSS scheme telling it to connect to a specific Gate One server (url):
//     GateOne.init({url: 'https://shell.mycompany.com/', 'theme': 'white'});
    // TIP: Did you know that the Gate One server doesn't have to be on the same domain as the page that loads gateone.js?  WebSockets don't have the same cross-domain restrictions that other DOM elements do.

    // Here's an example that limits the size of the #gateone element to demonstrate
    // how it can be embedded into another app/page...
//     GateOne.init({fillContainer: false, style: {'width': '50em', 'height': '32em'}, 'theme': 'white'});

    // Gate One uses relative sizes for all fonts and icons (e.g. 1em or 100%).  If you embed Gate One into your app and the fonts/icons seem too small you can adjust this by passing the fontSize parameter in the init() function:
    //     GateOne.init({fontSize: '130%'});
    // NOTE: Fonts *and* icons will be scaled according to the fontSize property.
}



// ################### BEGIN - ADD #########################

// For a given cookie, delete its expiration date
//
function deleteCookieExpiration(cookie_name)
{
  // The browser maintains the expiration date of the cookie. We can set the expiration date, but
  // when we get the cookie, we do not get the expiration date.
  //
  // As a result, getting the cookie value and then setting it again (without expiration date)
  // removes the expiration date from the cookie.
  //
  var cookieVal = getCookie(cookie_name);
  setCookie('gateone_user',cookieVal);
}

function getCookie ( cookie_name )
{
  var results = document.cookie.match ( '(^|;) ?' + cookie_name + '=([^;]*)(;|$)' );

  if ( results )
    return ( unescape ( results[2] ) );
  else
    return null;
}

function setCookie( name, value, exp_y, exp_m, exp_d, path, domain, secure )
{
  var cookie_string = name + "=" + escape ( value );

  if ( exp_y )
  {
    var expires = new Date ( exp_y, exp_m, exp_d );
    cookie_string += "; expires=" + expires.toGMTString();
  }

  if ( path )
        cookie_string += "; path=" + escape ( path );

  if ( domain )
        cookie_string += "; domain=" + escape ( domain );

  if ( secure )
        cookie_string += "; secure";

  document.cookie = cookie_string;
}
// ################### END - ADD #########################
</script>
</body>
</html>
```

Hope this helps you

**Comment by liftoff** [comment]
Using a cookie as a form of trusted authentication *is how the web works*.  Also, Gate One uses encrypted cookies so an attacker can't just make it up and give themselves whatever access they want.  They'd need the secret key on the Gate One server to do that.

I understand that some environments require sessions be extremely short-lived.  Gate One supports this out-of-the-box.  You can even disable sessions entirely but I don't recommend it because something as simple as a page reload or brief interruption in access can result in users losing their session.

If you need extremely short-lived sessions simply set the session_timeout in your 10server.conf to something like, "10s".  Ten seconds should be long enough to survive a momentary communications disruption or a page reload without running afoul of any security requirements.

**Comment by 123troy** [comment]
Setting the session_timeout to 10s did not work for us.  We even lowered it to 5s and 1s, still to no avail.  the application still held on to the authentication.  We use One Time Password (OTP) for logging into servers and network devices, so we had to make the above changes to allow OTP to work.

**Comment by hehaize** [comment]
How do I pass in the password?
