### ISSUE TITLE
GateOne Not Compatible with EL7 Linux Distros

### ISSUE THREAD

**Issue by ferricoxide** [liftoff/GateOne#560]
Note:

Already placed notes in #163 Appears that the Python 2.7 installation in EL7 (and presumably other distros) doesn't support `.pth` files:

```
# sh install-rpm.sh
running install
Checking .pth file support in usr/lib/python2.7/site-packages/
/bin/python -E -c pass
TEST FAILED: usr/lib/python2.7/site-packages/ does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from. 
```

This likely accounts for why, even though the downloadable RPM specifies `python >= 2.6`, the RPM still won't accept the EL7 Python RPM for satisfying the dependency.

**Comment by liftoff** [comment]
Do you have this problem with the latest Github code?  I posted a comment in that other issue about how to make an RPM but just in case:

    python setup.py bdist_rpm

That should make an RPM that should be installable on CentOS 7.  Note that to ensure compatibility need to run that command inside a CentOS 7.  If I run it on my Ubuntu workstation it'll make an RPM but it might not work in CentOS 7 because of the way rpmbuild works.

**Comment by ferricoxide** [comment]
Yes. I'd tried downloading the pre-rolled RPM and running the bdist_rpm script. The former failed on python dependency errors. The latter ran through with no errors but produced no RPMs. So I'd tried both the `sh install-rpm.sh` method from the top level of the `git clone`ed directory as well as trying a manual `rpmbuild` from the `spec` and archive files. It was in the latter two that I got the `.pth` support errors.

**Comment by ferricoxide** [comment]
Closing due to age (and haven't used GateOne in a year+, now).

**Comment by rharker** [comment]
Running into the exact same issue ... tried all the above workarounds -- sure would like to use gateone.
