### ISSUE TITLE
Issue of using url to start a new session.

### ISSUE THREAD

**Issue by sizeoftank** [liftoff/GateOne#644]
First I have a session of root@192.168.100.101 in my browser.
I want to start a browser tab for a new session (root@192.168.100.102) and entering the URL:
https://192.168.100.129:10443/?ssh=ssh://root@192.168.100.102
but it go to the old session (root@192.168.100.101)

Is here should be to create a new session?  (To root@192.168.100.102)

**Comment by liuning89757** [comment]
i met the same problem, have you got any solutions? @sizeoftank

**Comment by sizeoftank** [comment]
@liuning89757 
I hava a list of machines, at the beginning, I want to click one link to open a GateOne session, but I meets this issue.
And then I embedded Gate One into my project.
You can check the document: 
[http://liftoff.github.io/GateOne/Developer/embedding.html](http://liftoff.github.io/GateOne/Developer/embedding.html)

**Comment by liuning89757** [comment]
Thanks for your reply! 
Actualy i have read the doc before stuck in the problem, and i use `Gateone.init({... , autoConnectUrl: ssh://root@192.168.100.101, ...}) ` to open a ssh session instead of your method` (https://192.168.100.129:10443/?ssh=ssh://root@192.168.100.101).`  But  then i met the problem just like yours. 
Fortunately, i find the solution in issue #493 , and now it works well. :smile:
